name: Pulumi preview
on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        required: true
    secrets:
      GKE_SA_KEY:
        required: true
      GCP_PROJECT:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
jobs:
  pulumi-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ inputs.stack-name }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
